# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
 - script: yarn install
   displayName: 'Yarn install'
   workingDirectory: client

 - script: yarn run lerna run build-prod --scope @portfolio/shell
   displayName: 'Build Shell'
   workingDirectory: client
